apiVersion: v1
kind: Secret
metadata:
    name: argocd-notifications-secret
stringData:
    slack-token: xoxb-7618337865415-7639187312022-ubnJwqS1a8TF7OTqlxVvKnW8
    # https://argo-cd.readthedocs.io/en/stable/operator-manual/notifications/services/slack/