apiVersion: v1
kind: Secret
metadata:
    name: argocd-notifications-secret
stringData:
    slack-token: <slack-token>
    # https://argo-cd.readthedocs.io/en/stable/operator-manual/notifications/services/slack/