apiVersion: v1
kind: Service
metadata:
  name: front-service
  labels:
    name: frontend
spec:
  ports:
    - nodePort: 30004
      port: 80
      targetPort: 80
      protocol: TCP
  type: NodePort
  selector:
    app: frontend
---
apiVersion: apps/v1 #
kind: Deployment
metadata:
  name: front-deploy
spec:  #              
  selector:  # 
    matchLabels:
      app: frontend
  replicas: 2
  template:
    metadata:
      labels:  # 
        app: frontend
    spec:
      containers:
        - name: frontendcontainer
          image: us-central1-docker.pkg.dev/citric-period-433211-i6/appmanagercr/servermanagerfront:1.28
          ports:
            - containerPort: 80
      imagePullSecrets:
      - name: gcr-json-key

