prometheus:
  prometheusSpec:
    additionalScrapeConfigs:
      - job_name: "spring-actuator"
        metrics_path: "/actuator/prometheus"
        static_configs:
          - targets:
            - 34.70.132.118:30003
